apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default
data:
  bootstrap-servers: "YOUR_MSK_BOOTSTRAP_SERVERS"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
  namespace: default
data:
  dynamodb-notifications-table: "healthcare-notifications"
  dynamodb-sessions-table: "healthcare-sessions"
  s3-bucket: "YOUR_S3_BUCKET_NAME"
  region: "ap-south-1"